apiVersion: apps/v1
kind: Deployment
metadata:
     name: vote-deployment
spec:
    selector:
       matchLabels:
              name: vote-deployment
    template:
           metadata:
               name: vote-deployment
               labels:
                    name: vote-deployment
           spec:
                containers:
                  - image:
                    name: vote-deployment
#export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}') to get the node port