apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
   selector:
       matchLabels:
           name: worker
   template:
      metadata:
        name: worker
      spec:
        containers:
            - image: 
              name: worker