---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: iron-db
  labels:
    run: iron-db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
        - image: kodekloud/irondb:2.0
          name: iron-db
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: 'lychee'
            - name: MYSQL_USER
              value: 'lychee'
            - name: MYSQL_PASSWORD
              value: 'lychee'
            - name: MYSQL_ROOT_PASSWORD
              value: 'Braavo'
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      volumes:
      - name: db
        emptyDir: {}