apiVersion: v1
kind: Service
metadata:
   name: vote-service
   namespace: vote
spec:
   type: NodePort
   ports:
     - port: 5000
       targetPort: 80
       nodePort: 31000
   selector:
       name: vote-deployment
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#      name: vote-service
# subsets:
#     - addresses:
#          - ip:
#       ports:
#         - port:
