apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
   selector:
       matchLabels:
           name: redis-deployment
           name: db-deployment
   template:
      metadata:
        name: worker
        labels:
          name: redis-deployment
          name: db-deployment
      spec:
        containers:
            - image: kodekloud/examplevotingapp_worker
              name: worker