# kubectl create deployment worker --image=kodekloud/examplevotingapp_worker --dry-run -oyaml -n vote > worker.yaml
# Edit the container name, it won't take underscore in container name (examplevotingapp_worker). 

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: examplevotingapp-worker

